--[[
    Script Name    : SpawnScripts/Generic/AppearanceHuman.lua
    Script Author  : Rylec
    Script Date    : 2022.03.24 03:03:13
    Script Purpose : 
                   : 
--]]

local HumanAppearance_Type = 0

function humanAppearance(NPC)
    local HumanAppearance_Type = MakeRandomInt(23,23)

    if HumanAppearance_Type == 1 then
        SpawnSet(NPC, "skin_color", "241 232 234")
        SpawnSet(NPC, "soga_skin_color", "241 232 234") 
        SpawnSet(NPC, "eye_color", "61 120 89")
        SpawnSet(NPC, "soga_eye_color", "61 120 89") 
        SpawnSet(NPC, "hair_type_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
        SpawnSet(NPC, "hair_face_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_face_color", "0 0 0")
        SpawnSet(NPC, "hair_type_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "35 24 1") 
        SpawnSet(NPC, "hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "hair_color1", "38 22 21")
        SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
        SpawnSet(NPC, "hair_color2", "120 50 0")
        SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-42 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-42 0 0")       
        SpawnSet(NPC, "ear_type", "-63 29 0")   
        SpawnSet(NPC, "soga_ear_type", "-63 29 0")      
        SpawnSet(NPC, "eye_brow_type", "-57 83 29")   
        SpawnSet(NPC, "soga_eye_brow_type", "-57 83 29")      
        SpawnSet(NPC, "cheek_type", "21 14 0")   
        SpawnSet(NPC, "soga_cheek_type", "21 14 0")      
        SpawnSet(NPC, "lip_type", "95 -77 -50")   
        SpawnSet(NPC, "soga_lip_type", "95 -77 -50")      
        SpawnSet(NPC, "chin_type", "36 81 68")   
        SpawnSet(NPC, "soga_chin_type", "36 81 68")      
        SpawnSet(NPC, "nose_type", "65 68 -48")   
        SpawnSet(NPC, "soga_nose_type", "65 68 -48")      
    elseif HumanAppearance_Type == 2 then
        SpawnSet(NPC, "skin_color", "134 109 66")
        SpawnSet(NPC, "soga_skin_color", "134 109 66") 
        SpawnSet(NPC, "eye_color", "116 172 190")
        SpawnSet(NPC, "soga_eye_color", "116 172 190") 
        SpawnSet(NPC, "hair_type_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
        SpawnSet(NPC, "hair_face_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_face_color", "0 0 0")
        SpawnSet(NPC, "hair_type_highlight_color", "193 100 45")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "193 100 45") 
        SpawnSet(NPC, "hair_face_highlight_color", "193 100 45")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "193 100 45")
        SpawnSet(NPC, "hair_color1", "38 22 21")
        SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
        SpawnSet(NPC, "hair_color2", "120 50 0")
        SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
        SpawnSet(NPC, "hair_highlight", "105 26 26")
        SpawnSet(NPC, "soga_hair_highlight", "105 26 26")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "95 0 0")   
        SpawnSet(NPC, "soga_eye_type", "95 0 0")       
        SpawnSet(NPC, "ear_type", "-87 -74 0")   
        SpawnSet(NPC, "soga_ear_type", "-87 -74 0")      
        SpawnSet(NPC, "eye_brow_type", "97 -34 -4")   
        SpawnSet(NPC, "soga_eye_brow_type", "97 -34 -4")      
        SpawnSet(NPC, "cheek_type", "42 98 0")   
        SpawnSet(NPC, "soga_cheek_type", "42 98 0")      
        SpawnSet(NPC, "lip_type", "-22 18 -96")   
        SpawnSet(NPC, "soga_lip_type", "-22 18 -96")      
        SpawnSet(NPC, "chin_type", "-47 2 78")   
        SpawnSet(NPC, "soga_chin_type", "-47 2 78")      
        SpawnSet(NPC, "nose_type", "72 -42 56")   
        SpawnSet(NPC, "soga_nose_type", "72 -42 56")  
    elseif HumanAppearance_Type == 3 then
        SpawnSet(NPC, "skin_color", "202 194 179")
        SpawnSet(NPC, "soga_skin_color", "202 194 179") 
        SpawnSet(NPC, "eye_color", "116 172 190")
        SpawnSet(NPC, "soga_eye_color", "116 172 190") 
        SpawnSet(NPC, "hair_type_color", "2 0 0")
        SpawnSet(NPC, "soga_hair_type_color", "2 0 0") 
        SpawnSet(NPC, "hair_face_color", "2 0 0")
        SpawnSet(NPC, "soga_hair_face_color", "2 0 0")
        SpawnSet(NPC, "hair_type_highlight_color", "233 184 31")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "233 184 31") 
        SpawnSet(NPC, "hair_face_highlight_color", "233 184 31")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "233 184 31")
        SpawnSet(NPC, "hair_color1", "38 22 21")
        SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
        SpawnSet(NPC, "hair_color2", "120 50 0")
        SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
        SpawnSet(NPC, "hair_highlight", "246 219 114")
        SpawnSet(NPC, "soga_hair_highlight", "246 219 114")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "97 0 0")   
        SpawnSet(NPC, "soga_eye_type", "97 0 0")       
        SpawnSet(NPC, "ear_type", "-2 72 0")   
        SpawnSet(NPC, "soga_ear_type", "-2 72 0")      
        SpawnSet(NPC, "eye_brow_type", "93 -11 -52")   
        SpawnSet(NPC, "soga_eye_brow_type", "93 -11 -52")      
        SpawnSet(NPC, "cheek_type", "12 53 0")   
        SpawnSet(NPC, "soga_cheek_type", "12 53 0")      
        SpawnSet(NPC, "lip_type", "44 -53 -50")   
        SpawnSet(NPC, "soga_lip_type", "44 -53 -50")      
        SpawnSet(NPC, "chin_type", "41 -14 4")   
        SpawnSet(NPC, "soga_chin_type", "41 -14 4")      
        SpawnSet(NPC, "nose_type", "-55 -88 -62")   
        SpawnSet(NPC, "soga_nose_type", "-55 -88 -62")    
    elseif HumanAppearance_Type == 4 then
        SpawnSet(NPC, "skin_color", "234 195 198")
        SpawnSet(NPC, "soga_skin_color", "234 195 198") 
        SpawnSet(NPC, "eye_color", "102 74 34")
        SpawnSet(NPC, "soga_eye_color", "102 74 34") 
        SpawnSet(NPC, "hair_type_color", "5 2 2")
        SpawnSet(NPC, "soga_hair_type_color", "5 2 2") 
        SpawnSet(NPC, "hair_face_color", "5 2 2")
        SpawnSet(NPC, "soga_hair_face_color", "5 2 2")
        SpawnSet(NPC, "hair_type_highlight_color", "228 172 24")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "228 172 24") 
        SpawnSet(NPC, "hair_face_highlight_color", "228 172 24")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "228 172 24")
        SpawnSet(NPC, "hair_color1", "38 22 21")
        SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
        SpawnSet(NPC, "hair_color2", "120 50 0")
        SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
        SpawnSet(NPC, "hair_highlight", "200 165 96")
        SpawnSet(NPC, "soga_hair_highlight", "200 165 96")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "44 0 0")   
        SpawnSet(NPC, "soga_eye_type", "44 0 0")       
        SpawnSet(NPC, "ear_type", "14 -59 0")   
        SpawnSet(NPC, "soga_ear_type", "14 -59 0")      
        SpawnSet(NPC, "eye_brow_type", "58 -28 -48")   
        SpawnSet(NPC, "soga_eye_brow_type", "58 -28 -48")      
        SpawnSet(NPC, "cheek_type", "-81 -26 0")   
        SpawnSet(NPC, "soga_cheek_type", "-81 -26 0")      
        SpawnSet(NPC, "lip_type", "42 -89 0")   
        SpawnSet(NPC, "soga_lip_type", "42 -89 0")      
        SpawnSet(NPC, "chin_type", "18 -39 76")   
        SpawnSet(NPC, "soga_chin_type", "18 -39 76")      
        SpawnSet(NPC, "nose_type", "91 4 -29")   
        SpawnSet(NPC, "soga_nose_type", "91 4 -29") 
    elseif HumanAppearance_Type == 5 then
        SpawnSet(NPC, "skin_color", "231 193 194")
        SpawnSet(NPC, "soga_skin_color", "231 193 194") 
        SpawnSet(NPC, "eye_color", "33 64 50")
        SpawnSet(NPC, "soga_eye_color", "33 64 50") 
        SpawnSet(NPC, "hair_type_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
        SpawnSet(NPC, "hair_face_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
        SpawnSet(NPC, "hair_type_highlight_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "0 0 0") 
        SpawnSet(NPC, "hair_face_highlight_color", "0 0 0")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "0 0 0")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "38 22 21")
        SpawnSet(NPC, "soga_hair_highlight", "38 22 21")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-9 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-9 0 0")       
        SpawnSet(NPC, "ear_type", "-33 72 0")   
        SpawnSet(NPC, "soga_ear_type", "-33 72 0")      
        SpawnSet(NPC, "eye_brow_type", "95 52 36")   
        SpawnSet(NPC, "soga_eye_brow_type", "95 52 36")      
        SpawnSet(NPC, "cheek_type", "-82 16 0")   
        SpawnSet(NPC, "soga_cheek_type", "-82 16 0")      
        SpawnSet(NPC, "lip_type", "-91 -14 -19")   
        SpawnSet(NPC, "soga_lip_type", "-91 -14 -19")      
        SpawnSet(NPC, "chin_type", "58 31 -81")   
        SpawnSet(NPC, "soga_chin_type", "58 31 -81")      
        SpawnSet(NPC, "nose_type", "-44 12 -42")   
        SpawnSet(NPC, "soga_nose_type", "-44 12 -42") 
    elseif HumanAppearance_Type == 6 then
        SpawnSet(NPC, "skin_color", "245 250 250")
        SpawnSet(NPC, "soga_skin_color", "245 250 250") 
        SpawnSet(NPC, "eye_color", "119 175 191")
        SpawnSet(NPC, "soga_eye_color", "119 175 191") 
        SpawnSet(NPC, "hair_type_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
        SpawnSet(NPC, "hair_face_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
        SpawnSet(NPC, "hair_type_highlight_color", "47 14 19")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "47 14 19") 
        SpawnSet(NPC, "hair_face_highlight_color", "47 14 19")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "47 14 19")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "54 45 28")
        SpawnSet(NPC, "soga_hair_highlight", "54 45 28")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "76 0 0")   
        SpawnSet(NPC, "soga_eye_type", "76 0 0")       
        SpawnSet(NPC, "ear_type", "-9 -98 0")   
        SpawnSet(NPC, "soga_ear_type", "-9 -98 0")      
        SpawnSet(NPC, "eye_brow_type", "-91 -53 -25")   
        SpawnSet(NPC, "soga_eye_brow_type", "-91 -53 -25")      
        SpawnSet(NPC, "cheek_type", "45 -1 0")   
        SpawnSet(NPC, "soga_cheek_type", "45 -1 0")      
        SpawnSet(NPC, "lip_type", "-1 33 -22")   
        SpawnSet(NPC, "soga_lip_type", "-1 33 -22")      
        SpawnSet(NPC, "chin_type", "91 -12 1")   
        SpawnSet(NPC, "soga_chin_type", "91 -12 1")      
        SpawnSet(NPC, "nose_type", "91 53 -35")   
        SpawnSet(NPC, "soga_nose_type", "91 53 -35") 
    elseif HumanAppearance_Type == 7 then
        SpawnSet(NPC, "skin_color", "179 188 188")
        SpawnSet(NPC, "soga_skin_color", "179 188 188") 
        SpawnSet(NPC, "eye_color", "105 165 179")
        SpawnSet(NPC, "soga_eye_color", "105 165 179") 
        SpawnSet(NPC, "hair_type_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
        SpawnSet(NPC, "hair_face_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
        SpawnSet(NPC, "hair_type_highlight_color", "211 220 220")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "211 220 220") 
        SpawnSet(NPC, "hair_face_highlight_color", "211 220 220")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "211 220 220")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "161 165 168")
        SpawnSet(NPC, "soga_hair_highlight", "161 165 168")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "35 0 0")   
        SpawnSet(NPC, "soga_eye_type", "35 0 0")       
        SpawnSet(NPC, "ear_type", "68 -81 0")   
        SpawnSet(NPC, "soga_ear_type", "68 -81 0")      
        SpawnSet(NPC, "eye_brow_type", "-18 9 -39")   
        SpawnSet(NPC, "soga_eye_brow_type", "-18 9 -39")      
        SpawnSet(NPC, "cheek_type", "29 2 0")   
        SpawnSet(NPC, "soga_cheek_type", "29 2 0")      
        SpawnSet(NPC, "lip_type", "-29 63 8")   
        SpawnSet(NPC, "soga_lip_type", "-29 63 8")      
        SpawnSet(NPC, "chin_type", "72 -81 -58")   
        SpawnSet(NPC, "soga_chin_type", "72 -81 -58")      
        SpawnSet(NPC, "nose_type", "45 -79 -91")   
        SpawnSet(NPC, "soga_nose_type", "45 -79 -91") 
    elseif HumanAppearance_Type == 8 then
        SpawnSet(NPC, "skin_color", "211 199 150")
        SpawnSet(NPC, "soga_skin_color", "211 199 150") 
        SpawnSet(NPC, "eye_color", "57 120 128")
        SpawnSet(NPC, "soga_eye_color", "57 120 128") 
        SpawnSet(NPC, "hair_type_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
        SpawnSet(NPC, "hair_face_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
        SpawnSet(NPC, "hair_type_highlight_color", "244 246 246")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "244 246 246") 
        SpawnSet(NPC, "hair_face_highlight_color", "244 246 246")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "244 246 246")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "161 165 168")
        SpawnSet(NPC, "soga_hair_highlight", "161 165 168")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-71 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-71 0 0")       
        SpawnSet(NPC, "ear_type", "59 72 0")   
        SpawnSet(NPC, "soga_ear_type", "59 72 0")      
        SpawnSet(NPC, "eye_brow_type", "-68 -19 37")   
        SpawnSet(NPC, "soga_eye_brow_type", "-68 -19 37")      
        SpawnSet(NPC, "cheek_type", "-3 -57 0")   
        SpawnSet(NPC, "soga_cheek_type", "-3 -57 0")      
        SpawnSet(NPC, "lip_type", "78 -57 -61")   
        SpawnSet(NPC, "soga_lip_type", "78 -57 -61")      
        SpawnSet(NPC, "chin_type", "-69 68 4")   
        SpawnSet(NPC, "soga_chin_type", "-69 68 4")      
        SpawnSet(NPC, "nose_type", "83 -93 45")   
        SpawnSet(NPC, "soga_nose_type", "83 -93 45") 
    elseif HumanAppearance_Type == 9 then
        SpawnSet(NPC, "skin_color", "46 33 34")
        SpawnSet(NPC, "soga_skin_color", "46 33 34") 
        SpawnSet(NPC, "eye_color", "57 118 133")
        SpawnSet(NPC, "soga_eye_color", "57 118 133") 
        SpawnSet(NPC, "hair_type_color", "17 3 23")
        SpawnSet(NPC, "soga_hair_type_color", "17 3 23") 
        SpawnSet(NPC, "hair_face_color", "17 3 23")
        SpawnSet(NPC, "soga_hair_face_color", "17 3 23")
        SpawnSet(NPC, "hair_type_highlight_color", "168 59 22")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "168 59 22") 
        SpawnSet(NPC, "hair_face_highlight_color", "168 59 22")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "168 59 22")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "89 21 21")
        SpawnSet(NPC, "soga_hair_highlight", "89 21 21")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "70 0 0")   
        SpawnSet(NPC, "soga_eye_type", "70 0 0")       
        SpawnSet(NPC, "ear_type", "53 -55 0")   
        SpawnSet(NPC, "soga_ear_type", "53 -55 0")      
        SpawnSet(NPC, "eye_brow_type", "-72 -17 97")   
        SpawnSet(NPC, "soga_eye_brow_type", "-72 -17 97")      
        SpawnSet(NPC, "cheek_type", "79 -26 0")   
        SpawnSet(NPC, "soga_cheek_type", "79 -26 0")      
        SpawnSet(NPC, "lip_type", "-53 97 -22")   
        SpawnSet(NPC, "soga_lip_type", "-53 97 -22")      
        SpawnSet(NPC, "chin_type", "-9 61 65")   
        SpawnSet(NPC, "soga_chin_type", "-9 61 65")      
        SpawnSet(NPC, "nose_type", "-42 14 63")   
        SpawnSet(NPC, "soga_nose_type", "-42 14 63") 
    elseif HumanAppearance_Type == 10 then
        SpawnSet(NPC, "skin_color", "233 222 178")
        SpawnSet(NPC, "soga_skin_color", "233 222 178") 
        SpawnSet(NPC, "eye_color", "139 121 65")
        SpawnSet(NPC, "soga_eye_color", "139 121 65") 
        SpawnSet(NPC, "hair_type_color", "19 6 26")
        SpawnSet(NPC, "soga_hair_type_color", "19 6 26") 
        SpawnSet(NPC, "hair_face_color", "19 6 26")
        SpawnSet(NPC, "soga_hair_face_color", "19 6 26")
        SpawnSet(NPC, "hair_type_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "35 24 1") 
        SpawnSet(NPC, "hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "hair_color1", "29 21 28")
        SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
        SpawnSet(NPC, "hair_color2", "39 32 39")
        SpawnSet(NPC, "soga_hair_color2", "39 32 39") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "41 0 0")   
        SpawnSet(NPC, "soga_eye_type", "41 0 0")       
        SpawnSet(NPC, "ear_type", "63 -7 0")   
        SpawnSet(NPC, "soga_ear_type", "63 -7 0")      
        SpawnSet(NPC, "eye_brow_type", "38 79 -89")   
        SpawnSet(NPC, "soga_eye_brow_type", "38 79 -89")      
        SpawnSet(NPC, "cheek_type", "26 42 0")   
        SpawnSet(NPC, "soga_cheek_type", "26 42 0")      
        SpawnSet(NPC, "lip_type", "-72 62 -12")   
        SpawnSet(NPC, "soga_lip_type", "-72 62 -12")      
        SpawnSet(NPC, "chin_type", "44 -82 -52")   
        SpawnSet(NPC, "soga_chin_type", "44 -82 -52")      
        SpawnSet(NPC, "nose_type", "97 4 -45")   
        SpawnSet(NPC, "soga_nose_type", "97 4 -45") 
    elseif HumanAppearance_Type == 11 then
        SpawnSet(NPC, "skin_color", "47 38 39")
        SpawnSet(NPC, "soga_skin_color", "47 38 39") 
        SpawnSet(NPC, "eye_color", "108 145 107")
        SpawnSet(NPC, "soga_eye_color", "108 145 107") 
        SpawnSet(NPC, "hair_type_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_type_color", "35 24 1") 
        SpawnSet(NPC, "hair_face_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_face_color", "35 24 1")
        SpawnSet(NPC, "hair_type_highlight_color", "43 13 17")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "43 13 17") 
        SpawnSet(NPC, "hair_face_highlight_color", "43 13 17")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "43 13 17")
        SpawnSet(NPC, "hair_color1", "79 28 15")
        SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
        SpawnSet(NPC, "hair_color2", "111 64 0")
        SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
        SpawnSet(NPC, "hair_highlight", "54 45 28")
        SpawnSet(NPC, "soga_hair_highlight", "54 45 28")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "22 0 0")   
        SpawnSet(NPC, "soga_eye_type", "22 0 0")       
        SpawnSet(NPC, "ear_type", "-64 -2 0")   
        SpawnSet(NPC, "soga_ear_type", "-64 -2 0")      
        SpawnSet(NPC, "eye_brow_type", "-9 -65 41")   
        SpawnSet(NPC, "soga_eye_brow_type", "-9 -65 41")      
        SpawnSet(NPC, "cheek_type", "-37 69 0")   
        SpawnSet(NPC, "soga_cheek_type", "-37 69 0")      
        SpawnSet(NPC, "lip_type", "-76 -96 -65")   
        SpawnSet(NPC, "soga_lip_type", "-76 -96 -65")      
        SpawnSet(NPC, "chin_type", "-72 79 -39")   
        SpawnSet(NPC, "soga_chin_type", "-72 79 -39")      
        SpawnSet(NPC, "nose_type", "-55 68 29")   
        SpawnSet(NPC, "soga_nose_type", "-55 68 29") 
    elseif HumanAppearance_Type == 12 then
        SpawnSet(NPC, "skin_color", "245 249 245")
        SpawnSet(NPC, "soga_skin_color", "245 249 245") 
        SpawnSet(NPC, "eye_color", "43 70 43")
        SpawnSet(NPC, "soga_eye_color", "43 70 43") 
        SpawnSet(NPC, "hair_type_color", "37 22 5")
        SpawnSet(NPC, "soga_hair_type_color", "37 22 5") 
        SpawnSet(NPC, "hair_face_color", "37 22 5")
        SpawnSet(NPC, "soga_hair_face_color", "37 22 5")
        SpawnSet(NPC, "hair_type_highlight_color", "121 38 35")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "121 38 35") 
        SpawnSet(NPC, "hair_face_highlight_color", "121 38 35")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "121 38 35")
        SpawnSet(NPC, "hair_color1", "79 28 15")
        SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
        SpawnSet(NPC, "hair_color2", "111 64 0")
        SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
        SpawnSet(NPC, "hair_highlight", "91 21 51")
        SpawnSet(NPC, "soga_hair_highlight", "91 21 51")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "11 0 0")   
        SpawnSet(NPC, "soga_eye_type", "11 0 0")       
        SpawnSet(NPC, "ear_type", "63 -26 0")   
        SpawnSet(NPC, "soga_ear_type", "63 -26 0")      
        SpawnSet(NPC, "eye_brow_type", "-65 -81 -4")   
        SpawnSet(NPC, "soga_eye_brow_type", "-65 -81 -4")      
        SpawnSet(NPC, "cheek_type", "1 -4 0")   
        SpawnSet(NPC, "soga_cheek_type", "1 -4 0")      
        SpawnSet(NPC, "lip_type", "41 47 -72")   
        SpawnSet(NPC, "soga_lip_type", "41 47 -72")      
        SpawnSet(NPC, "chin_type", "-51 97 4")   
        SpawnSet(NPC, "soga_chin_type", "-51 97 4")      
        SpawnSet(NPC, "nose_type", "97 62 -14")   
        SpawnSet(NPC, "soga_nose_type", "97 62 -14") 
    elseif HumanAppearance_Type == 13 then
        SpawnSet(NPC, "skin_color", "177 159 108")
        SpawnSet(NPC, "soga_skin_color", "177 159 108") 
        SpawnSet(NPC, "eye_color", "163 201 212")
        SpawnSet(NPC, "soga_eye_color", "163 201 212") 
        SpawnSet(NPC, "hair_type_color", "40 20 7")
        SpawnSet(NPC, "soga_hair_type_color", "40 20 7") 
        SpawnSet(NPC, "hair_face_color", "40 20 7")
        SpawnSet(NPC, "soga_hair_face_color", "40 20 7")
        SpawnSet(NPC, "hair_type_highlight_color", "47 42 59")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "47 42 59") 
        SpawnSet(NPC, "hair_face_highlight_color", "47 42 59")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "47 42 59")
        SpawnSet(NPC, "hair_color1", "79 28 15")
        SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
        SpawnSet(NPC, "hair_color2", "111 64 0")
        SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
        SpawnSet(NPC, "hair_highlight", "43 36 70")
        SpawnSet(NPC, "soga_hair_highlight", "43 36 70")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "97 0 0")   
        SpawnSet(NPC, "soga_eye_type", "97 0 0")       
        SpawnSet(NPC, "ear_type", "-50 78 0")   
        SpawnSet(NPC, "soga_ear_type", "-50 78 0")      
        SpawnSet(NPC, "eye_brow_type", "-72 37 24")   
        SpawnSet(NPC, "soga_eye_brow_type", "-72 37 24")      
        SpawnSet(NPC, "cheek_type", "4 -91 0")   
        SpawnSet(NPC, "soga_cheek_type", "4 -91 0")      
        SpawnSet(NPC, "lip_type", "-35 -68 -36")   
        SpawnSet(NPC, "soga_lip_type", "-35 -68 -36")      
        SpawnSet(NPC, "chin_type", "-70 7 76")   
        SpawnSet(NPC, "soga_chin_type", "-70 7 76")      
        SpawnSet(NPC, "nose_type", "64 -31 58")   
        SpawnSet(NPC, "soga_nose_type", "64 -31 58") 
    elseif HumanAppearance_Type == 14 then
        SpawnSet(NPC, "skin_color", "177 186 186")
        SpawnSet(NPC, "soga_skin_color", "177 186 186") 
        SpawnSet(NPC, "eye_color", "150 193 203")
        SpawnSet(NPC, "soga_eye_color", "150 193 203") 
        SpawnSet(NPC, "hair_type_color", "42 29 3")
        SpawnSet(NPC, "soga_hair_type_color", "42 29 3") 
        SpawnSet(NPC, "hair_face_color", "42 29 3")
        SpawnSet(NPC, "soga_hair_face_color", "42 29 3")
        SpawnSet(NPC, "hair_type_highlight_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "15 1 21") 
        SpawnSet(NPC, "hair_face_highlight_color", "15 1 21")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "15 1 21")
        SpawnSet(NPC, "hair_color1", "79 28 15")
        SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
        SpawnSet(NPC, "hair_color2", "111 64 0")
        SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
        SpawnSet(NPC, "hair_highlight", "29 21 28")
        SpawnSet(NPC, "soga_hair_highlight", "29 21 28")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "31 0 0")   
        SpawnSet(NPC, "soga_eye_type", "31 0 0")       
        SpawnSet(NPC, "ear_type", "70 -95 0")   
        SpawnSet(NPC, "soga_ear_type", "70 -95 0")      
        SpawnSet(NPC, "eye_brow_type", "-42 17 22")   
        SpawnSet(NPC, "soga_eye_brow_type", "-42 17 22")      
        SpawnSet(NPC, "cheek_type", "72 -63 0")   
        SpawnSet(NPC, "soga_cheek_type", "72 -63 0")      
        SpawnSet(NPC, "lip_type", "1 85 9")   
        SpawnSet(NPC, "soga_lip_type", "1 85 9")      
        SpawnSet(NPC, "chin_type", "7 25 45")   
        SpawnSet(NPC, "soga_chin_type", "7 25 45")      
        SpawnSet(NPC, "nose_type", "89 58 26")   
        SpawnSet(NPC, "soga_nose_type", "89 58 26") 
    elseif HumanAppearance_Type == 15 then
        SpawnSet(NPC, "skin_color", "243 251 251")
        SpawnSet(NPC, "soga_skin_color", "243 251 251") 
        SpawnSet(NPC, "eye_color", "173 142 88")
        SpawnSet(NPC, "soga_eye_color", "173 142 88") 
        SpawnSet(NPC, "hair_type_color", "49 47 61")
        SpawnSet(NPC, "soga_hair_type_color", "49 47 61") 
        SpawnSet(NPC, "hair_face_color", "49 47 61")
        SpawnSet(NPC, "soga_hair_face_color", "49 47 61")
        SpawnSet(NPC, "hair_type_highlight_color", "42 29 2")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "42 29 2") 
        SpawnSet(NPC, "hair_face_highlight_color", "42 29 2")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "42 29 2")
        SpawnSet(NPC, "hair_color1", "43 36 70")
        SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
        SpawnSet(NPC, "hair_color2", "64 76 74")
        SpawnSet(NPC, "soga_hair_color2", "64 76 74") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-77 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-77 0 0")       
        SpawnSet(NPC, "ear_type", "-61 -84 0")   
        SpawnSet(NPC, "soga_ear_type", "-61 -84 0")      
        SpawnSet(NPC, "eye_brow_type", "-52 -36 -32")   
        SpawnSet(NPC, "soga_eye_brow_type", "-52 -36 -32")      
        SpawnSet(NPC, "cheek_type", "-44 -72 0")   
        SpawnSet(NPC, "soga_cheek_type", "-44 -72 0")      
        SpawnSet(NPC, "lip_type", "4 42 71")   
        SpawnSet(NPC, "soga_lip_type", "4 42 71")      
        SpawnSet(NPC, "chin_type", "39 -75 78")   
        SpawnSet(NPC, "soga_chin_type", "39 -75 78")      
        SpawnSet(NPC, "nose_type", "-48 83 31")   
        SpawnSet(NPC, "soga_nose_type", "-48 83 31") 
    elseif HumanAppearance_Type == 16 then
        SpawnSet(NPC, "skin_color", "186 191 170")
        SpawnSet(NPC, "soga_skin_color", "186 191 170") 
        SpawnSet(NPC, "eye_color", "38 77 88")
        SpawnSet(NPC, "soga_eye_color", "38 77 88") 
        SpawnSet(NPC, "hair_type_color", "59 58 73")
        SpawnSet(NPC, "soga_hair_type_color", "59 58 73") 
        SpawnSet(NPC, "hair_face_color", "59 58 73")
        SpawnSet(NPC, "soga_hair_face_color", "59 58 73")
        SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147") 
        SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
        SpawnSet(NPC, "hair_color1", "43 36 70")
        SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
        SpawnSet(NPC, "hair_color2", "64 76 74")
        SpawnSet(NPC, "soga_hair_color2", "64 76 74") 
        SpawnSet(NPC, "hair_highlight", "114 112 142")
        SpawnSet(NPC, "soga_hair_highlight", "114 112 142")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-53 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-53 0 0")       
        SpawnSet(NPC, "ear_type", "-70 72 0")   
        SpawnSet(NPC, "soga_ear_type", "-70 72 0")      
        SpawnSet(NPC, "eye_brow_type", "44 31 -93")   
        SpawnSet(NPC, "soga_eye_brow_type", "44 31 -93")      
        SpawnSet(NPC, "cheek_type", "81 -56 0")   
        SpawnSet(NPC, "soga_cheek_type", "81 -56 0")      
        SpawnSet(NPC, "lip_type", "29 35 -2")   
        SpawnSet(NPC, "soga_lip_type", "29 35 -2")      
        SpawnSet(NPC, "chin_type", "-76 -25 39")   
        SpawnSet(NPC, "soga_chin_type", "-76 -25 39")      
        SpawnSet(NPC, "nose_type", "29 -85 -97")   
        SpawnSet(NPC, "soga_nose_type", "29 -85 -97") 
    elseif HumanAppearance_Type == 17 then
        SpawnSet(NPC, "skin_color", "239 239 209")
        SpawnSet(NPC, "soga_skin_color", "239 239 209") 
        SpawnSet(NPC, "eye_color", "120 175 192")
        SpawnSet(NPC, "soga_eye_color", "120 175 192") 
        SpawnSet(NPC, "hair_type_color", "83 57 8")
        SpawnSet(NPC, "soga_hair_type_color", "83 57 8") 
        SpawnSet(NPC, "hair_face_color", "83 57 8")
        SpawnSet(NPC, "soga_hair_face_color", "83 57 8")
        SpawnSet(NPC, "hair_type_highlight_color", "19 6 25")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "19 6 25") 
        SpawnSet(NPC, "hair_face_highlight_color", "19 6 25")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "19 6 25")
        SpawnSet(NPC, "hair_color1", "56 33 26")
        SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
        SpawnSet(NPC, "hair_color2", "94 59 11")
        SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
        SpawnSet(NPC, "hair_highlight", "29 21 28")
        SpawnSet(NPC, "soga_hair_highlight", "29 21 28")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "17 0 0")   
        SpawnSet(NPC, "soga_eye_type", "17 0 0")       
        SpawnSet(NPC, "ear_type", "-72 94 0")   
        SpawnSet(NPC, "soga_ear_type", "-72 94 0")      
        SpawnSet(NPC, "eye_brow_type", "-55 -97 -44")   
        SpawnSet(NPC, "soga_eye_brow_type", "-55 -97 -44")      
        SpawnSet(NPC, "cheek_type", "-17 79 0")   
        SpawnSet(NPC, "soga_cheek_type", "-17 79 0")      
        SpawnSet(NPC, "lip_type", "6 -39 88")   
        SpawnSet(NPC, "soga_lip_type", "6 -39 88")      
        SpawnSet(NPC, "chin_type", "-77 -97 -83")   
        SpawnSet(NPC, "soga_chin_type", "-77 -97 -83")      
        SpawnSet(NPC, "nose_type", "-66 -68 3")   
        SpawnSet(NPC, "soga_nose_type", "-66 -68 3") 
    elseif HumanAppearance_Type == 18 then
        SpawnSet(NPC, "skin_color", "136 118 120")
        SpawnSet(NPC, "soga_skin_color", "136 118 120") 
        SpawnSet(NPC, "eye_color", "84 139 114")
        SpawnSet(NPC, "soga_eye_color", "84 139 114") 
        SpawnSet(NPC, "hair_type_color", "84 0 0")
        SpawnSet(NPC, "soga_hair_type_color", "84 0 0") 
        SpawnSet(NPC, "hair_face_color", "84 0 0")
        SpawnSet(NPC, "soga_hair_face_color", "84 0 0")
        SpawnSet(NPC, "hair_type_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "35 24 1") 
        SpawnSet(NPC, "hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "35 24 1")
        SpawnSet(NPC, "hair_color1", "109 14 49")
        SpawnSet(NPC, "soga_hair_color1", "109 14 49") 
        SpawnSet(NPC, "hair_color2", "185 97 0")
        SpawnSet(NPC, "soga_hair_color2", "185 97 0") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-62 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-62 0 0")       
        SpawnSet(NPC, "ear_type", "58 -64 0")   
        SpawnSet(NPC, "soga_ear_type", "58 -64 0")      
        SpawnSet(NPC, "eye_brow_type", "-21 71 29")   
        SpawnSet(NPC, "soga_eye_brow_type", "-21 71 29")      
        SpawnSet(NPC, "cheek_type", "-3 39 0")   
        SpawnSet(NPC, "soga_cheek_type", "-3 39 0")      
        SpawnSet(NPC, "lip_type", "-79 83 -85")   
        SpawnSet(NPC, "soga_lip_type", "-79 83 -85")      
        SpawnSet(NPC, "chin_type", "58 -75 -96")   
        SpawnSet(NPC, "soga_chin_type", "58 -75 -96")      
        SpawnSet(NPC, "nose_type", "3 42 55")   
        SpawnSet(NPC, "soga_nose_type", "3 42 55") 
    elseif HumanAppearance_Type == 19 then
        SpawnSet(NPC, "skin_color", "215 195 159")
        SpawnSet(NPC, "soga_skin_color", "215 195 159") 
        SpawnSet(NPC, "eye_color", "166 144 94")
        SpawnSet(NPC, "soga_eye_color", "166 144 94") 
        SpawnSet(NPC, "hair_type_color", "84 0 0")
        SpawnSet(NPC, "soga_hair_type_color", "84 0 0") 
        SpawnSet(NPC, "hair_face_color", "84 0 0")
        SpawnSet(NPC, "soga_hair_face_color", "84 0 0")
        SpawnSet(NPC, "hair_type_highlight_color", "40 19 9")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "40 19 9") 
        SpawnSet(NPC, "hair_face_highlight_color", "40 19 9")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "40 19 9")
        SpawnSet(NPC, "hair_color1", "109 14 49")
        SpawnSet(NPC, "soga_hair_color1", "109 14 49") 
        SpawnSet(NPC, "hair_color2", "185 97 0")
        SpawnSet(NPC, "soga_hair_color2", "185 97 0") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-72 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-72 0 0")       
        SpawnSet(NPC, "ear_type", "-97 34 0")   
        SpawnSet(NPC, "soga_ear_type", "-97 34 0")      
        SpawnSet(NPC, "eye_brow_type", "-25 97 21")   
        SpawnSet(NPC, "soga_eye_brow_type", "-25 97 21")      
        SpawnSet(NPC, "cheek_type", "-78 -3 0")   
        SpawnSet(NPC, "soga_cheek_type", "-78 -3 0")      
        SpawnSet(NPC, "lip_type", "8 -52 85")   
        SpawnSet(NPC, "soga_lip_type", "8 -52 85")      
        SpawnSet(NPC, "chin_type", "-29 14 -63")   
        SpawnSet(NPC, "soga_chin_type", "-29 14 -63")      
        SpawnSet(NPC, "nose_type", "-50 -61 -59")   
        SpawnSet(NPC, "soga_nose_type", "-50 -61 -59") 
    elseif HumanAppearance_Type == 20 then
        SpawnSet(NPC, "skin_color", "171 148 98")
        SpawnSet(NPC, "soga_skin_color", "171 148 98") 
        SpawnSet(NPC, "eye_color", "36 77 77")
        SpawnSet(NPC, "soga_eye_color", "36 77 77") 
        SpawnSet(NPC, "hair_type_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
        SpawnSet(NPC, "hair_face_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
        SpawnSet(NPC, "hair_type_highlight_color", "114 31 28")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "114 31 28") 
        SpawnSet(NPC, "hair_face_highlight_color", "114 31 28")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "114 31 28")
        SpawnSet(NPC, "hair_color1", "56 33 26")
        SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
        SpawnSet(NPC, "hair_color2", "94 59 11")
        SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
        SpawnSet(NPC, "hair_highlight", "91 21 51")
        SpawnSet(NPC, "soga_hair_highlight", "91 21 51")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-87 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-87 0 0")       
        SpawnSet(NPC, "ear_type", "-93 96 0")   
        SpawnSet(NPC, "soga_ear_type", "-93 96 0")      
        SpawnSet(NPC, "eye_brow_type", "59 -88 -45")   
        SpawnSet(NPC, "soga_eye_brow_type", "59 -88 -45")      
        SpawnSet(NPC, "cheek_type", "-81 85 0")   
        SpawnSet(NPC, "soga_cheek_type", "-81 85 0")      
        SpawnSet(NPC, "lip_type", "28 -58 -66")   
        SpawnSet(NPC, "soga_lip_type", "28 -58 -66")      
        SpawnSet(NPC, "chin_type", "76 -88 -66")   
        SpawnSet(NPC, "soga_chin_type", "76 -88 -66")      
        SpawnSet(NPC, "nose_type", "-22 -87 -39")   
        SpawnSet(NPC, "soga_nose_type", "-22 -87 -39") 
    elseif HumanAppearance_Type == 21 then
        SpawnSet(NPC, "skin_color", "244 237 237")
        SpawnSet(NPC, "soga_skin_color", "244 237 237") 
        SpawnSet(NPC, "eye_color", "55 117 121")
        SpawnSet(NPC, "soga_eye_color", "55 117 121") 
        SpawnSet(NPC, "hair_type_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
        SpawnSet(NPC, "hair_face_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
        SpawnSet(NPC, "hair_type_highlight_color", "232 169 28")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "232 169 28") 
        SpawnSet(NPC, "hair_face_highlight_color", "232 169 28")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "232 169 28")
        SpawnSet(NPC, "hair_color1", "56 33 26")
        SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
        SpawnSet(NPC, "hair_color2", "94 59 11")
        SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
        SpawnSet(NPC, "hair_highlight", "200 165 96")
        SpawnSet(NPC, "soga_hair_highlight", "200 165 96")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "48 0 0")   
        SpawnSet(NPC, "soga_eye_type", "48 0 0")       
        SpawnSet(NPC, "ear_type", "19 -48 0")   
        SpawnSet(NPC, "soga_ear_type", "19 -48 0")      
        SpawnSet(NPC, "eye_brow_type", "19 -26 1")   
        SpawnSet(NPC, "soga_eye_brow_type", "19 -26 1")      
        SpawnSet(NPC, "cheek_type", "9 16 0")   
        SpawnSet(NPC, "soga_cheek_type", "9 16 0")      
        SpawnSet(NPC, "lip_type", "61 21 -39")   
        SpawnSet(NPC, "soga_lip_type", "61 21 -39")      
        SpawnSet(NPC, "chin_type", "57 14 78")   
        SpawnSet(NPC, "soga_chin_type", "57 14 78")      
        SpawnSet(NPC, "nose_type", "-84 74 41")   
        SpawnSet(NPC, "soga_nose_type", "-84 74 41") 
    elseif HumanAppearance_Type == 22 then
        SpawnSet(NPC, "skin_color", "105 112 109")
        SpawnSet(NPC, "soga_skin_color", "105 112 109") 
        SpawnSet(NPC, "eye_color", "41 82 95")
        SpawnSet(NPC, "soga_eye_color", "41 82 95") 
        SpawnSet(NPC, "hair_type_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
        SpawnSet(NPC, "hair_face_color", "100 70 10")
        SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
        SpawnSet(NPC, "hair_type_highlight_color", "232 183 30")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "232 183 30") 
        SpawnSet(NPC, "hair_face_highlight_color", "232 183 30")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "232 183 30")
        SpawnSet(NPC, "hair_color1", "56 33 26")
        SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
        SpawnSet(NPC, "hair_color2", "94 59 11")
        SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
        SpawnSet(NPC, "hair_highlight", "246 219 114")
        SpawnSet(NPC, "soga_hair_highlight", "246 219 114")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "79 0 0")   
        SpawnSet(NPC, "soga_eye_type", "79 0 0")       
        SpawnSet(NPC, "ear_type", "19 21 0")   
        SpawnSet(NPC, "soga_ear_type", "19 21 0")      
        SpawnSet(NPC, "eye_brow_type", "29 89 17")   
        SpawnSet(NPC, "soga_eye_brow_type", "29 89 17")      
        SpawnSet(NPC, "cheek_type", "-7 -94 0")   
        SpawnSet(NPC, "soga_cheek_type", "-7 -94 0")      
        SpawnSet(NPC, "lip_type", "-57 -2 -35")   
        SpawnSet(NPC, "soga_lip_type", "-57 -2 -35")      
        SpawnSet(NPC, "chin_type", "68 -72 -13")   
        SpawnSet(NPC, "soga_chin_type", "68 -72 -13")      
        SpawnSet(NPC, "nose_type", "18 18 2")   
        SpawnSet(NPC, "soga_nose_type", "18 18 2") 
    elseif HumanAppearance_Type == 23 then
        SpawnSet(NPC, "skin_color", "228 177 149")
        SpawnSet(NPC, "soga_skin_color", "228 177 149") 
        SpawnSet(NPC, "eye_color", "144 188 195")
        SpawnSet(NPC, "soga_eye_color", "144 188 195") 
        SpawnSet(NPC, "hair_type_color", "121 38 35")
        SpawnSet(NPC, "soga_hair_type_color", "121 38 35") 
        SpawnSet(NPC, "hair_face_color", "121 38 35")
        SpawnSet(NPC, "soga_hair_face_color", "121 38 35")
        SpawnSet(NPC, "hair_type_highlight_color", "47 33 3")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "47 33 3") 
        SpawnSet(NPC, "hair_face_highlight_color", "47 33 3")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "47 33 3")
        SpawnSet(NPC, "hair_color1", "91 21 51")
        SpawnSet(NPC, "soga_hair_color1", "91 21 51") 
        SpawnSet(NPC, "hair_color2", "159 88 0")
        SpawnSet(NPC, "soga_hair_color2", "159 88 0") 
        SpawnSet(NPC, "hair_highlight", "79 28 15")
        SpawnSet(NPC, "soga_hair_highlight", "79 28 15")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "62 0 0")   
        SpawnSet(NPC, "soga_eye_type", "62 0 0")       
        SpawnSet(NPC, "ear_type", "-42 -59 0")   
        SpawnSet(NPC, "soga_ear_type", "-42 -59 0")      
        SpawnSet(NPC, "eye_brow_type", "93 19 -8")   
        SpawnSet(NPC, "soga_eye_brow_type", "93 19 -8")      
        SpawnSet(NPC, "cheek_type", "-24 -34 0")   
        SpawnSet(NPC, "soga_cheek_type", "-24 -34 0")      
        SpawnSet(NPC, "lip_type", "-8 9 58")   
        SpawnSet(NPC, "soga_lip_type", "-8 9 58")      
        SpawnSet(NPC, "chin_type", "-34 -89 -55")   
        SpawnSet(NPC, "soga_chin_type", "-34 -89 -55")      
        SpawnSet(NPC, "nose_type", "-4 18 82")   
        SpawnSet(NPC, "soga_nose_type", "-4 18 82") 
    elseif HumanAppearance_Type == 24 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 25 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 26 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 27 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 28 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 29 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 30 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 31 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 32 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 33 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 34 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 35 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 36 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 37 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 38 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 39 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 40 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 41 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 42 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 43 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 44 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    elseif HumanAppearance_Type == 45 then
        SpawnSet(NPC, "skin_color", "")
        SpawnSet(NPC, "soga_skin_color", "") 
        SpawnSet(NPC, "eye_color", "")
        SpawnSet(NPC, "soga_eye_color", "") 
        SpawnSet(NPC, "hair_type_color", "")
        SpawnSet(NPC, "soga_hair_type_color", "") 
        SpawnSet(NPC, "hair_face_color", "")
        SpawnSet(NPC, "soga_hair_face_color", "")
        SpawnSet(NPC, "hair_type_highlight_color", "")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "") 
        SpawnSet(NPC, "hair_face_highlight_color", "")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "")
        SpawnSet(NPC, "hair_color1", "")
        SpawnSet(NPC, "soga_hair_color1", "") 
        SpawnSet(NPC, "hair_color2", "")
        SpawnSet(NPC, "soga_hair_color2", "") 
        SpawnSet(NPC, "hair_highlight", "")
        SpawnSet(NPC, "soga_hair_highlight", "")    
        SpawnSet(NPC, "model_color", "")   
        SpawnSet(NPC, "soga_model_color", "")     
        SpawnSet(NPC, "eye_type", "")   
        SpawnSet(NPC, "soga_eye_type", "")       
        SpawnSet(NPC, "ear_type", "")   
        SpawnSet(NPC, "soga_ear_type", "")      
        SpawnSet(NPC, "eye_brow_type", "")   
        SpawnSet(NPC, "soga_eye_brow_type", "")      
        SpawnSet(NPC, "cheek_type", "")   
        SpawnSet(NPC, "soga_cheek_type", "")      
        SpawnSet(NPC, "lip_type", "")   
        SpawnSet(NPC, "soga_lip_type", "")      
        SpawnSet(NPC, "chin_type", "")   
        SpawnSet(NPC, "soga_chin_type", "")      
        SpawnSet(NPC, "nose_type", "")   
        SpawnSet(NPC, "soga_nose_type", "") 
    end

--[[    These appearances looks weird
    elseif HumanAppearance_Type == 4 then
        SpawnSet(NPC, "skin_color", "44 46 46")
        SpawnSet(NPC, "soga_skin_color", "44 46 46") 
        SpawnSet(NPC, "eye_color", "145 190 203")
        SpawnSet(NPC, "soga_eye_color", "145 190 203") 
        SpawnSet(NPC, "hair_type_color", "4 1 1")
        SpawnSet(NPC, "soga_hair_type_color", "4 1 1") 
        SpawnSet(NPC, "hair_face_color", "4 1 1")
        SpawnSet(NPC, "soga_hair_face_color", "4 1 1")
        SpawnSet(NPC, "hair_type_highlight_color", "233 168 29")
        SpawnSet(NPC, "soga_hair_type_highlight_color", "233 168 29") 
        SpawnSet(NPC, "hair_face_highlight_color", "233 168 29")
        SpawnSet(NPC, "soga_hair_face_highlight_color", "233 168 29")
        SpawnSet(NPC, "hair_color1", "38 22 21")
        SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
        SpawnSet(NPC, "hair_color2", "120 50 0")
        SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
        SpawnSet(NPC, "hair_highlight", "200 165 96")
        SpawnSet(NPC, "soga_hair_highlight", "200 165 96")    
        SpawnSet(NPC, "model_color", "229 229 102")   
        SpawnSet(NPC, "soga_model_color", "229 229 102")     
        SpawnSet(NPC, "eye_type", "-31 0 0")   
        SpawnSet(NPC, "soga_eye_type", "-31 0 0")       
        SpawnSet(NPC, "ear_type", "-96 -34 0")   
        SpawnSet(NPC, "soga_ear_type", "-96 -34 0")      
        SpawnSet(NPC, "eye_brow_type", "-72 -72 41")   
        SpawnSet(NPC, "soga_eye_brow_type", "-72 -72 41")      
        SpawnSet(NPC, "cheek_type", "-31 -82 0")   
        SpawnSet(NPC, "soga_cheek_type", "-31 -82 0")      
        SpawnSet(NPC, "lip_type", "12 -37 66")   
        SpawnSet(NPC, "soga_lip_type", "12 -37 66")      
        SpawnSet(NPC, "chin_type", "-69 -29 85")   
        SpawnSet(NPC, "soga_chin_type", "-69 -29 85")      
        SpawnSet(NPC, "nose_type", "-19 -9 -82")   
        SpawnSet(NPC, "soga_nose_type", "-19 -9 -82") 







--]]
end

