--[[
    Script Name    : SpawnScripts/qeynos_combined02/aGraystoneGuildbruiserDojoBarbarian570757.lua
    Script Author  : Rylec
    Script Date    : 2021.03.07 06:03:16
    Script Purpose : 
                   : 
--]]

function spawn(NPC)
    local model = MakeRandomInt(1,2)
        if model == 1 then
            SetModelType(NPC, "132") -- human female
            SpawnSet(NPC, "soga_model_type", "132")
            SpawnSet(NPC, "chest_type", "5529")
            SpawnSet(NPC, "legs_type", "5530")
            HumanCosmetics(NPC)
        elseif model == 2 then
            SetModelType(NPC, "134") -- human male
            SpawnSet(NPC, "soga_model_type", "134")
            SpawnSet(NPC, "chest_type", "5533")
            SpawnSet(NPC, "legs_type", "5534")
            HumanCosmetics(NPC)
        elseif model == 3 then
            SetModelType(NPC, "109") -- dwarf female
            SpawnSet(NPC, "soga_model_type", "109")
            SpawnSet(NPC, "chest_type", "5473")
            SpawnSet(NPC, "legs_type", "5474")
            DwarfCosmetics(NPC)
        elseif model == 4 then
            SetModelType(NPC, "110") -- dwarf male
            SpawnSet(NPC, "soga_model_type", "110")
            SpawnSet(NPC, "chest_type", "5477")
            SpawnSet(NPC, "legs_type", "5478")
            DwarfCosmetics(NPC)
        elseif model == 5 then
            SetModelType(NPC, "111") -- barbarian female
            SpawnSet(NPC, "soga_model_type", "111")
            SpawnSet(NPC, "chest_type", "5457")
            SpawnSet(NPC, "legs_type", "5458")
            BarbarianCosmetics(NPC)
        else
            local BarbarianMale = MakeRandomInt(1467,1471)
            SetModelType(NPC, "112") -- barbarian male
            SpawnSet(NPC, "soga_model_type", "112")
            SpawnSet(NPC, "chest_type", "5461")
            SpawnSet(NPC, "legs_type", "5462")
            BarbarianCosmetics(NPC)
        end
        
    SetEquipment(NPC, 3, 991, 255, 255, 255, 255, 255, 255)
    SetEquipment(NPC, 5, 0)
    SetEquipment(NPC, 6, 1010, 255, 255, 255, 255, 255, 255)
    SetEquipment(NPC, 7, 4570, 255, 255, 255, 255, 255, 255)
    SetEquipment(NPC, 8, 992, 255, 255, 255, 255, 255, 255)
end

function hailed(NPC, Spawn)
    FaceTarget(NPC, Spawn)
end

function respawn(NPC)
    spawn(NPC)
end






function HumanCosmetics(NPC)

    local hair = MakeRandomInt(1121,1140)

        SpawnSet(NPC, "hair_type", hair)
        SpawnSet(NPC, "soga_hair_type", hair)

    local beard = MakeRandomInt(1164,1191)
    local beard_chance = MakeRandomInt(1,100)    

        if beard_chance < 51 then
            SpawnSet(NPC, "facial_hair_type", "0")
            SpawnSet(NPC, "soga_facial_hair_type", "0")
        else
            SpawnSet(NPC, "facial_hair_type", beard)
            SpawnSet(NPC, "soga_facial_hair_type", beard)
        end

    local overall_look = MakeRandomInt(1,14)
 
        if overall_look == 1 then -- Bright yellow
            SpawnSet(NPC, "skin_color", "206 162 137")
            SpawnSet(NPC, "soga_skin_color", "206 162 137") 
            SpawnSet(NPC, "eye_color", "47 100 102")
            SpawnSet(NPC, "soga_eye_color", "47 100 102") 
            SpawnSet(NPC, "hair_type_color", "194 164 6")
            SpawnSet(NPC, "soga_hair_type_color", "194 164 6") 
            SpawnSet(NPC, "hair_face_color", "194 164 6")
            SpawnSet(NPC, "soga_hair_face_color", "194 164 6")
            SpawnSet(NPC, "hair_type_highlight_color", "188 168 37")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "188 168 37") 
            SpawnSet(NPC, "hair_face_highlight_color", "188 168 37")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "188 168 37")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")
        elseif overall_look == 2 then -- Extra light chestnut (towards yellow)
            SpawnSet(NPC, "skin_color", "241 245 221")
            SpawnSet(NPC, "soga_skin_color", "241 245 221") 
            SpawnSet(NPC, "eye_color", "38 65 40")
            SpawnSet(NPC, "soga_eye_color", "38 65 40") 
            SpawnSet(NPC, "hair_type_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_type_color", "100 70 10") 
            SpawnSet(NPC, "hair_face_color", "100 70 10")
            SpawnSet(NPC, "soga_hair_face_color", "100 70 10")
            SpawnSet(NPC, "hair_type_highlight_color", "231 170 26")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "231 170 26") 
            SpawnSet(NPC, "hair_face_highlight_color", "231 170 26")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "231 170 26")
            SpawnSet(NPC, "hair_color1", "56 33 26")
            SpawnSet(NPC, "soga_hair_color1", "56 33 26") 
            SpawnSet(NPC, "hair_color2", "94 59 11")
            SpawnSet(NPC, "soga_hair_color2", "94 59 11") 
            SpawnSet(NPC, "hair_highlight", "200 165 96")
            SpawnSet(NPC, "soga_hair_highlight", "200 165 96")  
        elseif overall_look == 3 then -- Light orange
            SpawnSet(NPC, "skin_color", "210 188 159")
            SpawnSet(NPC, "soga_skin_color", "210 188 159") 
            SpawnSet(NPC, "eye_color", "74 130 98")
            SpawnSet(NPC, "soga_eye_color", "74 130 98") 
            SpawnSet(NPC, "hair_type_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_type_color", "184 128 10") 
            SpawnSet(NPC, "hair_face_color", "184 128 10")
            SpawnSet(NPC, "soga_hair_face_color", "184 128 10")
            SpawnSet(NPC, "hair_type_highlight_color", "37 10 14")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "37 10 14") 
            SpawnSet(NPC, "hair_face_highlight_color", "37 10 14")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "37 10 14")
            SpawnSet(NPC, "hair_color1", "213 84 34")
            SpawnSet(NPC, "soga_hair_color1", "213 84 34") 
            SpawnSet(NPC, "hair_color2", "2 0 0")
            SpawnSet(NPC, "soga_hair_color2", "2 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 4 then -- Orange with bright highlights
            SpawnSet(NPC, "skin_color", "234 244 244")
            SpawnSet(NPC, "soga_skin_color", "234 244 244") 
            SpawnSet(NPC, "eye_color", "37 76 88")
            SpawnSet(NPC, "soga_eye_color", "37 76 88") 
            SpawnSet(NPC, "hair_type_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_type_color", "121 38 35") 
            SpawnSet(NPC, "hair_face_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_face_color", "121 38 35")
            SpawnSet(NPC, "hair_type_highlight_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "233 184 31") 
            SpawnSet(NPC, "hair_face_highlight_color", "233 184 31")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "233 184 31")
            SpawnSet(NPC, "hair_color1", "91 21 51")
            SpawnSet(NPC, "soga_hair_color1", "91 21 51") 
            SpawnSet(NPC, "hair_color2", "159 88 0")
            SpawnSet(NPC, "soga_hair_color2", "159 88 0") 
            SpawnSet(NPC, "hair_highlight", "246 219 114")
            SpawnSet(NPC, "soga_hair_highlight", "246 219 114") 
        elseif overall_look == 5 then -- Light chestnut
            SpawnSet(NPC, "skin_color", "245 249 245")
            SpawnSet(NPC, "soga_skin_color", "245 249 245") 
            SpawnSet(NPC, "eye_color", "43 70 43")
            SpawnSet(NPC, "soga_eye_color", "43 70 43") 
            SpawnSet(NPC, "hair_type_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_type_color", "37 22 5") 
            SpawnSet(NPC, "hair_face_color", "37 22 5")
            SpawnSet(NPC, "soga_hair_face_color", "37 22 5")
            SpawnSet(NPC, "hair_type_highlight_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "121 38 35") 
            SpawnSet(NPC, "hair_face_highlight_color", "121 38 35")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "121 38 35")
            SpawnSet(NPC, "hair_color1", "79 28 15")
            SpawnSet(NPC, "soga_hair_color1", "79 28 15") 
            SpawnSet(NPC, "hair_color2", "111 64 0")
            SpawnSet(NPC, "soga_hair_color2", "111 64 0") 
            SpawnSet(NPC, "hair_highlight", "91 21 51")
            SpawnSet(NPC, "soga_hair_highlight", "91 21 51")  
        elseif overall_look == 6 then -- Chestnut
            SpawnSet(NPC, "skin_color", "241 245 221")
            SpawnSet(NPC, "soga_skin_color", "241 245 221") 
            SpawnSet(NPC, "eye_color", "102 154 140")
            SpawnSet(NPC, "soga_eye_color", "102 154 140") 
            SpawnSet(NPC, "hair_type_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_type_color", "0 0 0") 
            SpawnSet(NPC, "hair_face_color", "0 0 0")
            SpawnSet(NPC, "soga_hair_face_color", "0 0 0")
            SpawnSet(NPC, "hair_type_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "15 1 21") 
            SpawnSet(NPC, "hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "15 1 21")
            SpawnSet(NPC, "hair_color1", "38 22 21")
            SpawnSet(NPC, "soga_hair_color1", "38 22 21") 
            SpawnSet(NPC, "hair_color2", "120 50 0")
            SpawnSet(NPC, "soga_hair_color2", "120 50 0") 
            SpawnSet(NPC, "hair_highlight", "29 21 28")
            SpawnSet(NPC, "soga_hair_highlight", "29 21 28") 
        elseif overall_look == 7 then -- Chestnut and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "40 20 7")
            SpawnSet(NPC, "soga_hair_type_color", "40 20 7") 
            SpawnSet(NPC, "hair_face_color", "40 20 7")
            SpawnSet(NPC, "soga_hair_face_color", "40 20 7")
            SpawnSet(NPC, "hair_type_highlight_color", "47 42 59")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "47 42 59") 
            SpawnSet(NPC, "hair_face_highlight_color", "47 42 59")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "47 42 59")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 8 then -- Dark brown
            SpawnSet(NPC, "skin_color", "176 156 105")
            SpawnSet(NPC, "soga_skin_color", "176 156 105") 
            SpawnSet(NPC, "eye_color", "67 132 116")
            SpawnSet(NPC, "soga_eye_color", "67 132 116") 
            SpawnSet(NPC, "hair_type_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_type_color", "33 24 12") 
            SpawnSet(NPC, "hair_face_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_face_color", "33 24 12")
            SpawnSet(NPC, "hair_type_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "11 6 1") 
            SpawnSet(NPC, "hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")    
        elseif overall_look == 9 then -- Dark brown and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_type_color", "33 24 12") 
            SpawnSet(NPC, "hair_face_color", "33 24 12")
            SpawnSet(NPC, "soga_hair_face_color", "33 24 12")
            SpawnSet(NPC, "hair_type_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "11 6 1") 
            SpawnSet(NPC, "hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "11 6 1")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0")  
        elseif overall_look == 10 then -- Lige grey towards white
            SpawnSet(NPC, "skin_color", "181 132 94")
            SpawnSet(NPC, "soga_skin_color", "181 132 94") 
            SpawnSet(NPC, "eye_color", "31 68 69")
            SpawnSet(NPC, "soga_eye_color", "31 68 69") 
            SpawnSet(NPC, "hair_type_color", "213 209 159")
            SpawnSet(NPC, "soga_hair_type_color", "213 209 159") 
            SpawnSet(NPC, "hair_face_color", "213 209 159")
            SpawnSet(NPC, "soga_hair_face_color", "213 209 159")
            SpawnSet(NPC, "hair_type_highlight_color", "56 40 19")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "56 40 19") 
            SpawnSet(NPC, "hair_face_highlight_color", "56 40 19")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "56 40 19")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        elseif overall_look == 11 then -- Dark grey 
            SpawnSet(NPC, "skin_color", "186 191 170")
            SpawnSet(NPC, "soga_skin_color", "186 191 170") 
            SpawnSet(NPC, "eye_color", "38 77 88")
            SpawnSet(NPC, "soga_eye_color", "38 77 88") 
            SpawnSet(NPC, "hair_type_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_type_color", "59 58 73") 
            SpawnSet(NPC, "hair_face_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_face_color", "59 58 73")
            SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147") 
            SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_color1", "43 36 70")
            SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
            SpawnSet(NPC, "hair_color2", "64 76 74")
            SpawnSet(NPC, "soga_hair_color2", "64 76 74")
            SpawnSet(NPC, "hair_highlight", "114 112 142")
            SpawnSet(NPC, "soga_hair_highlight", "114 112 142")
        elseif overall_look == 12 then -- Dark grey and brown skin
            SpawnSet(NPC, "skin_color", "46 35 12")
            SpawnSet(NPC, "soga_skin_color", "46 35 12") 
            SpawnSet(NPC, "eye_color", "105 85 44")
            SpawnSet(NPC, "soga_eye_color", "105 85 44") 
            SpawnSet(NPC, "hair_type_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_type_color", "59 58 73") 
            SpawnSet(NPC, "hair_face_color", "59 58 73")
            SpawnSet(NPC, "soga_hair_face_color", "59 58 73")
            SpawnSet(NPC, "hair_type_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "119 147 147") 
            SpawnSet(NPC, "hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "119 147 147")
            SpawnSet(NPC, "hair_color1", "43 36 70")
            SpawnSet(NPC, "soga_hair_color1", "43 36 70") 
            SpawnSet(NPC, "hair_color2", "64 76 74")
            SpawnSet(NPC, "soga_hair_color2", "64 76 74")
            SpawnSet(NPC, "hair_highlight", "114 112 142")
            SpawnSet(NPC, "soga_hair_highlight", "114 112 142")
        elseif overall_look == 13 then -- Black with white highlights
            SpawnSet(NPC, "skin_color", "179 188 188")
            SpawnSet(NPC, "soga_skin_color", "179 188 188") 
            SpawnSet(NPC, "eye_color", "105 165 179")
            SpawnSet(NPC, "soga_eye_color", "105 165 179") 
            SpawnSet(NPC, "hair_type_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_type_color", "15 1 21") 
            SpawnSet(NPC, "hair_face_color", "15 1 21")
            SpawnSet(NPC, "soga_hair_face_color", "15 1 21")
            SpawnSet(NPC, "hair_type_highlight_color", "211 220 220")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "211 220 220") 
            SpawnSet(NPC, "hair_face_highlight_color", "211 220 220")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "211 220 220")
            SpawnSet(NPC, "hair_color1", "29 21 28")
            SpawnSet(NPC, "soga_hair_color1", "29 21 28") 
            SpawnSet(NPC, "hair_color2", "39 32 39")
            SpawnSet(NPC, "soga_hair_color2", "39 32 39")
            SpawnSet(NPC, "hair_highlight", "161 165 168")
            SpawnSet(NPC, "soga_hair_highlight", "161 165 168")
         else -- Light black
            SpawnSet(NPC, "skin_color", "176 156 105")
            SpawnSet(NPC, "soga_skin_color", "176 156 105") 
            SpawnSet(NPC, "eye_color", "67 132 116")
            SpawnSet(NPC, "soga_eye_color", "67 132 116") 
            SpawnSet(NPC, "hair_type_color", "39 50 50")
            SpawnSet(NPC, "soga_hair_type_color", "39 50 50") 
            SpawnSet(NPC, "hair_face_color", "39 50 50")
            SpawnSet(NPC, "soga_hair_face_color", "39 50 50")
            SpawnSet(NPC, "hair_type_highlight_color", "18 11 0")
            SpawnSet(NPC, "soga_hair_type_highlight_color", "18 11 0") 
            SpawnSet(NPC, "hair_face_highlight_color", "18 11 0")
            SpawnSet(NPC, "soga_hair_face_highlight_color", "18 11 0")
            SpawnSet(NPC, "hair_color1", "0 0 0")
            SpawnSet(NPC, "soga_hair_color1", "0 0 0") 
            SpawnSet(NPC, "hair_color2", "0 0 0")
            SpawnSet(NPC, "soga_hair_color2", "0 0 0") 
            SpawnSet(NPC, "hair_highlight", "0 0 0")
            SpawnSet(NPC, "soga_hair_highlight", "0 0 0") 
        end
end

